### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by antoniogarrote**
- Improved TermFactory with better support for literals
- Fixed problem with initial value of the StartQuery iterator

Pending sync with Java library

### CODE REVIEW

**Comment by HolgerKnublauch** [comment]
Given the failures above, I assume this is still work in progress?

**Comment by HolgerKnublauch** [comment]
BTW there are slight changes to dash.js and dash.ttl at https://github.com/TopQuadrant/shacl/commit/bf00c3c2dc2717a8e02551168c2ba84b76a6c3b7

When copying dash.ttl note that the references to tosh need to be removed for the version bundled with shacl-js (3 lines).

**Comment by antoniogarrote** [comment]
The problem was the sync check in the build. If it finds a different version of the shared ttl or js files the build fails automatically.
It will always happen if I make changes in one file and they are not yet merged into master in the Java project.

I have removed the references to tosh from  dash.ttl. You already removed the sync check for that particular file.

I have made a small test re-writing rdfquery in typescript: 
https://github.com/antoniogarrote/rdfquery-standalone 

Wondering if having a stand-alone version of rdfquery that can be referenced from both projects is a direction you would like to explore. It might make the full process of managing changes in the common dependency easier. Also adding some static typing on the library is a nice add-on.

**Comment by HolgerKnublauch** [comment]
I have not used typescript but I do agree with the benefits of strong typing. rdfquery had always been conceived to be potentially stand-alone. It's a simple library that may be of general use. If you think it would be worthwhile doing this separation, then go ahead, but I may not be able to help much on this given my other commitments and being more on the Java side of things. As long as there is an easy way to get the necessary .js file(s) so that I can copy it over into the other projects, and as long as the test cases still pass, I am fine.

**Pull request merged**
